import React, { useEffect, useState } from 'react';
import { saveAs } from 'file-saver'
import { mockImage } from '../../utils.js';

import './Model.css'

const Model = () => {
    const [imageState, setImageState] = useState({
        currIndex: null,
        images: []
    })

    const fetchImage = () => {
        setTimeout(() => {
            const fetchedImage = mockImage()
            setImageState({ currIndex: imageState.currIndex + 1, images: [...imageState.images, fetchedImage] })
        }, 1000)
    }


    useEffect(() => {
        setTimeout(() => {
            const fetchedImage = mockImage()
            setImageState({ currIndex: 0, images: [fetchedImage] })
        }, 1000)
    }, [])

    const downlaodImage = (img) => {
        saveAs(img, 'image.jpg')
    }

    const currentImage = imageState.images[imageState.currIndex]

    return (
        <section className="modelContainer">
            <div className="modelImgContainer">
                <img width="300" alt="Image generated by kunstig" src={currentImage} />
            </div>
            <div className="modelButtonGroup">
                <div className="modelButtonContainer">
                    <button className="modelButton" onClick={fetchImage}>nytt bilde</button>
                </div>
                <div className="modelButtonContainer">
                    <button className="modelButton" onClick={() => downlaodImage(currentImage)}>last ned</button>
                </div>

            </div>
        </section>
    );
}

export default Model;
