# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy kunstig frontend to Azure Web App - glup-stig-fewa

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: 'glup-stig-fewa'
  AZURE_WEBAPP_PACKAGE_PATH: 'build'
  NODE_VERSION: '14.x' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: false
      
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_311FCFDCB2A347F885FCF5C64EF4B9E4 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
